// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as playbook$0 from "./internal/playbook/models.js";

/**
 * BundleDTO 是打开后的 bundle 视图
 */
export interface BundleDTO {
    "archive": string;
    "workDir": string;
    "main": string;
    "summary": playbook$0.ConfSummary;
    "conf": ConfDTO | null;
    "files": playbook$0.FileInfo[] | null;
    "tree": (playbook$0.TreeNode | null)[] | null;
    "taskPaths": string[] | null;
    "dirty": string[] | null;
}

/**
 * ConfDTO 是 playbook.conf 的可编辑视图
 */
export interface ConfDTO {
    "summary": playbook$0.ConfSummary;
    "fields": playbook$0.ConfField[] | null;
    "attrs": playbook$0.ConfAttrItem[] | null;
    "pages": playbook$0.ConfOptionPage[] | null;
    "packages": playbook$0.ConfPackage[] | null;
    "options": string[] | null;
    "raw": string;
}

/**
 * SaveResult 保存结果
 */
export interface SaveResult {
    "archive": string;
    "size": number;
    "files": number;
}

/**
 * SchemaDTO 是 action 类型定义
 */
export interface SchemaDTO {
    "tags": playbook$0.TagSpec[] | null;
    "common": playbook$0.FieldSpec[] | null;
    "groups": string[] | null;
    "privileges": string[] | null;
    "runAsOptions": string[] | null;
    "registryTypes": string[] | null;
}

/**
 * StartupDTO 命令行/文件关联传入的启动参数
 */
export interface StartupDTO {
    "archive": string;
    "password": string;
}

/**
 * StatusDTO 应用/环境状态
 */
export interface StatusDTO {
    "sevenZip": string;
    "sevenZipOk": boolean;

    /**
     * builtin | system | custom
     */
    "sevenZipSource": string;
    "hasBundle": boolean;
    "archive": string;
    "dirty": boolean;
    "lastOpenDir": string;
}
