// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlaybookService 暴露给前端的服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as playbook$0 from "./internal/playbook/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAction 新增 action
 */
export function AddAction(rel: string, index: number, tag: string, fields: playbook$0.KeyValue[] | null, flow: boolean): $CancellablePromise<playbook$0.Task | null> {
    return $Call.ByID(1691148323, rel, index, tag, fields, flow);
}

/**
 * AttachWindow 绑定窗口并挂上关闭拦截（有未保存修改时交给前端确认）
 */
export function AttachWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3766424683, w);
}

/**
 * Bundle 返回当前 bundle
 */
export function Bundle(): $CancellablePromise<$models.BundleDTO | null> {
    return $Call.ByID(269900482);
}

/**
 * CloseBundle 关闭并清理临时目录
 */
export function CloseBundle(): $CancellablePromise<void> {
    return $Call.ByID(2995805654);
}

/**
 * DuplicateAction 复制 action
 */
export function DuplicateAction(rel: string, index: number): $CancellablePromise<playbook$0.Task | null> {
    return $Call.ByID(3322449321, rel, index);
}

/**
 * ExportWorkspace 把解包内容导出到指定目录（便于用外部工具查看）
 */
export function ExportWorkspace(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1847783669, dir);
}

/**
 * MoveAction 移动 action
 */
export function MoveAction(rel: string, $from: number, to: number): $CancellablePromise<playbook$0.Task | null> {
    return $Call.ByID(3643827325, rel, $from, to);
}

/**
 * OpenBundle 解包并载入 playbook
 */
export function OpenBundle(archive: string, password: string): $CancellablePromise<$models.BundleDTO | null> {
    return $Call.ByID(1983960394, archive, password);
}

/**
 * PickArchive 选择 .apbx 文件
 */
export function PickArchive(): $CancellablePromise<string> {
    return $Call.ByID(4223346019);
}

/**
 * PickSavePath 选择保存位置
 */
export function PickSavePath(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(600684573, defaultName);
}

/**
 * ReadFile 读取 bundle 内任意文件
 */
export function ReadFile(rel: string): $CancellablePromise<string> {
    return $Call.ByID(2367551252, rel);
}

/**
 * Reload 丢弃修改并重新解包
 */
export function Reload(): $CancellablePromise<$models.BundleDTO | null> {
    return $Call.ByID(2633573807);
}

/**
 * RemoveAction 删除 action
 */
export function RemoveAction(rel: string, index: number): $CancellablePromise<playbook$0.Task | null> {
    return $Call.ByID(115864004, rel, index);
}

/**
 * RemoveField 删除 action 字段
 */
export function RemoveField(rel: string, index: number, key: string): $CancellablePromise<playbook$0.Task | null> {
    return $Call.ByID(287920730, rel, index, key);
}

/**
 * RevealInExplorer 在资源管理器中打开
 */
export function RevealInExplorer(p: string): $CancellablePromise<void> {
    return $Call.ByID(457184379, p);
}

/**
 * Save 写回并重新打包；out 为空时覆盖原文件
 */
export function Save(out: string): $CancellablePromise<$models.SaveResult | null> {
    return $Call.ByID(1882387287, out);
}

/**
 * SaveFile 写入 bundle 内任意文件
 */
export function SaveFile(rel: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(90660713, rel, content);
}

/**
 * Schema 返回 action 类型定义
 */
export function Schema(): $CancellablePromise<$models.SchemaDTO> {
    return $Call.ByID(2970871541);
}

/**
 * SetConfAttr 修改 conf 元素属性
 */
export function SetConfAttr(tag: string, occurrence: number, attr: string, value: string): $CancellablePromise<$models.ConfDTO | null> {
    return $Call.ByID(3997978563, tag, occurrence, attr, value);
}

/**
 * SetConfRaw 源码模式替换 conf
 */
export function SetConfRaw(text: string): $CancellablePromise<$models.ConfDTO | null> {
    return $Call.ByID(3303410726, text);
}

/**
 * SetConfText 修改 conf 元素文本
 */
export function SetConfText(tag: string, occurrence: number, value: string): $CancellablePromise<$models.ConfDTO | null> {
    return $Call.ByID(3731235959, tag, occurrence, value);
}

/**
 * SetMeta 修改任务元数据
 */
export function SetMeta(rel: string, key: string, value: string): $CancellablePromise<playbook$0.Task | null> {
    return $Call.ByID(309438567, rel, key, value);
}

/**
 * SetSevenZipPath 手动指定 7z 路径
 */
export function SetSevenZipPath(p: string): $CancellablePromise<void> {
    return $Call.ByID(3005537573, p);
}

/**
 * SetStartupArgs 记录命令行传入的归档路径与密码（文件关联/自动化用）
 */
export function SetStartupArgs(archive: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(3343044906, archive, password);
}

/**
 * SetTaskText 源码模式整体替换
 */
export function SetTaskText(rel: string, text: string): $CancellablePromise<playbook$0.Task | null> {
    return $Call.ByID(1817322112, rel, text);
}

/**
 * StartupFile 取出并清空启动参数
 */
export function StartupFile(): $CancellablePromise<$models.StartupDTO> {
    return $Call.ByID(4132490401);
}

/**
 * Status 返回当前状态
 */
export function Status(): $CancellablePromise<$models.StatusDTO> {
    return $Call.ByID(1672302996);
}

/**
 * Task 读取一个任务文件
 */
export function Task(rel: string): $CancellablePromise<playbook$0.Task | null> {
    return $Call.ByID(1151058951, rel);
}

/**
 * UpdateField 修改/新增 action 字段
 */
export function UpdateField(rel: string, index: number, key: string, value: string, kind: string): $CancellablePromise<playbook$0.Task | null> {
    return $Call.ByID(750697245, rel, index, key, value, kind);
}

/**
 * Validate 执行校验
 */
export function Validate(): $CancellablePromise<playbook$0.Issue[] | null> {
    return $Call.ByID(2442407556);
}

/**
 * WindowCloseRequest 前端点击自绘关闭按钮
 */
export function WindowCloseRequest(): $CancellablePromise<string> {
    return $Call.ByID(454464911);
}

/**
 * WindowForceClose 确认丢弃修改后真正关闭
 */
export function WindowForceClose(): $CancellablePromise<void> {
    return $Call.ByID(3434690363);
}

/**
 * WindowIsMaximised 当前是否最大化
 */
export function WindowIsMaximised(): $CancellablePromise<boolean> {
    return $Call.ByID(2463614299);
}

/**
 * WindowMinimise 最小化
 */
export function WindowMinimise(): $CancellablePromise<void> {
    return $Call.ByID(2984009931);
}

/**
 * WindowToggleMaximise 最大化/还原
 */
export function WindowToggleMaximise(): $CancellablePromise<boolean> {
    return $Call.ByID(711622425);
}
