// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Action 是 actions 序列中的一项，如 `- !registryValue: {...}`
 */
export interface Action {
    "index": number;

    /**
     * 去掉 ! 与尾部 :
     */
    "tag": string;

    /**
     * 流式 {..}
     */
    "flow": boolean;
    "fields": Field[] | null;
    "line": number;

    /**
     * 源码区间（1-based，含）
     */
    "spanStart": number;
    "spanEnd": number;

    /**
     * 注释块起始行
     */
    "headFrom": number;

    /**
     * '-' 所在列(0-based)
     */
    "indent": number;

    /**
     * 子键缩进
     */
    "child": number;
    "raw": string;

    /**
     * 上方注释文本
     */
    "note": string;
    "option": string;
    "options"?: string[] | null;
    "weight": number;
}

/**
 * ConfAttrItem 是可编辑的元素属性
 */
export interface ConfAttrItem {
    "tag": string;
    "occurrence": number;
    "path": string;
    "name": string;
    "value": string;
}

/**
 * ConfField 是可编辑的叶子元素
 */
export interface ConfField {
    "tag": string;
    "occurrence": number;
    "path": string;
    "label": string;
    "value": string;

    /**
     * text | bool
     */
    "kind": string;
}

/**
 * ConfOptionItem 是 FeaturePages 中的一个选项
 */
export interface ConfOptionItem {
    "tag": string;
    "occurrence": number;
    "name": string;
    "nameOccurrence": number;
    "text": string;
    "textOccurrence": number;
    "isChecked": boolean;
    "hasChecked": boolean;
    "isNone": boolean;
}

/**
 * ConfOptionPage 是 FeaturePages 中的一页
 */
export interface ConfOptionPage {
    "tag": string;
    "occurrence": number;

    /**
     * checkbox | radio | radioImage
     */
    "kind": string;
    "description": string;
    "isRequired": boolean;
    "defaultOption": string;
    "dependsOn": string;
    "options": ConfOptionItem[] | null;
}

/**
 * SoftwarePackages 解析 Software 段
 */
export interface ConfPackage {
    "option": string;
    "name": string;
    "title": string;
    "description": string;
    "icon": string;
    "defaultWebBrowser": boolean;
}

/**
 * ConfSummary 用于界面展示的基本信息
 */
export interface ConfSummary {
    "name": string;
    "username": string;
    "title": string;
    "version": string;
    "uniqueId": string;
    "description": string;
    "shortDescription": string;
    "details": string;
    "productCode": string;
    "git": string;
    "website": string;
    "donateLink": string;
    "upgradableFrom": string;
    "supportedBuilds": string[] | null;
    "requirements": string[] | null;
}

/**
 * Field 是 action 的一个键值对
 */
export interface Field {
    "key": string;

    /**
     * scalar | list | map | block
     */
    "kind": string;
    "value": string;

    /**
     * YAML 解析 tag，如 !!bool / !!int / !!str
     */
    "tag": string;
    "items"?: string[] | null;

    /**
     * 源位置（1-based）
     */
    "line": number;
    "column": number;
    "keyCol": number;
}

/**
 * FieldSpec 描述一个 action 字段
 */
export interface FieldSpec {
    "key": string;
    "label": string;

    /**
     * text | textarea | int | bool | enum | list
     */
    "kind": string;
    "enum"?: string[] | null;
    "required": boolean;
    "help"?: string;
    "placeholder"?: string;
}

/**
 * FileInfo 描述 bundle 内的一个文件
 */
export interface FileInfo {
    /**
     * bundle 内相对路径（反斜杠）
     */
    "path": string;
    "size": number;
    "isYml": boolean;
}

/**
 * Issue 是一条校验结果
 */
export interface Issue {
    /**
     * error | warning | info
     */
    "level": string;
    "file": string;
    "line": number;
    "index": number;
    "tag": string;
    "message": string;
}

/**
 * KeyValue 是新增 action 时的字段
 */
export interface KeyValue {
    "key": string;
    "value": string;

    /**
     * Kind: auto | string | int | bool | list；为空按 auto
     */
    "kind": string;
}

/**
 * TagSpec 描述一种 action 类型
 */
export interface TagSpec {
    "tag": string;
    "title": string;
    "group": string;

    /**
     * 新增时默认用流式写法
     */
    "flow": boolean;
    "fields": FieldSpec[] | null;
}

/**
 * Task 是一个 YAML 任务文件
 */
export interface Task {
    "path": string;

    /**
     * 当前文本（LF）
     */
    "text": string;
    "meta": TaskMeta;
    "actions": Action[] | null;
}

export interface TaskMeta {
    "title": string;
    "description": string;
    "privilege": string;
    "onUpgrade": boolean;
    "dependsOn": string[] | null;
}

/**
 * TreeNode 是展开后的任务树
 */
export interface TreeNode {
    "path": string;
    "include": string;
    "title": string;
    "description": string;
    "privilege": string;
    "actionCount": number;
    "missing": boolean;
    "cycle": boolean;
    "children": (TreeNode | null)[] | null;
}
